### ISSUE TITLE
Syncswap - Response Error

### ISSUE THREAD

**Issue by RamonReis** [delta-hq/l2-lxp-liquidity-reward#120]
V2_SUBGRAPH_URL = "https://gateway-arbitrum.network.thegraph.com/api/ce0ba3625ebbbd3c4b5a2af394dc8e47/subgraphs/id/3xpZFx5YNWzqemwdtRhyaTXVidKNnjY19XAWoHtvR6Lh"

Stack trace:
```
An error occurred for block [object Object]: SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
[2024-05-09, 18:15:34 UTC] {{task_log_fetcher.py:63}} INFO - [2024-05-09 18:15:16,265]     at JSON.parse (<anonymous>)
INFO - [2024-05-09 18:15:16,265]     at JSON.parse (<anonymous>)
INFO - [2024-05-09 18:15:16,265]     at parseJSONFromBytes (node:internal/deps/undici/undici:4306:19)
INFO - [2024-05-09 18:15:16,265]     at successSteps (node:internal/deps/undici/undici:4288:27)
INFO - [2024-05-09 18:15:16,265]     at fullyReadBody (node:internal/deps/undici/undici:2724:9)
INFO - [2024-05-09 18:15:16,265]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
INFO - [2024-05-09 18:15:16,265]     at async consumeBody (node:internal/deps/undici/undici:4297:7)
INFO - [2024-05-09 18:15:16,265]     at async getV2UserPositionsAtBlock (/project/tvl_adapters/adapters/syncswap/dist/sdk/lib.js:61:50)
INFO - [2024-05-09 18:15:16,265]     at async getUserTVLByBlock (/project/tvl_adapters/adapters/syncswap/dist/index.js:45:25)
INFO - [2024-05-09 18:15:16,265]     at async /project/tvl_adapters/adapters/syncswap/dist/index.js:103:28
```

**Comment by amedrontadora** [comment]
#121 I updated the subgraph request url
