### ISSUE TITLE
3ADao - Issue

### ISSUE THREAD

**Issue by 0xroll** [delta-hq/l2-lxp-liquidity-reward#176]
hi @bytes0xcr6 , can you check the adapter . we are getting this error atm

[2024-05-24, 09:51:40 UTC] {{task_log_fetcher.py:63}} INFO - [2024-05-24 09:51:14,509] 2024-05-24 09:51:14,509 WARNING root An error occurred for block 4747275: Error: server response 504 Gateway Time-out (request={  }, response={  }, error=null, info={ "requestUrl": "https://rpc.linea.build/", "responseBody": "error code: 504", "responseStatus": "504 Gateway Time-out" }, code=SERVER_ERROR, version=6.12.1)
[2024-05-24, 09:51:40 UTC] {{task_log_fetcher.py:63}} INFO - [2024-05-24 09:51:14,509]     at makeError (/project/tvl_adapters/adapters/protocol3adao/node_modules/ethers/lib.commonjs/utils/errors.js:129:21)
[2024-05-24, 09:51:40 UTC] {{task_log_fetcher.py:63}} INFO - [2024-05-24 09:51:14,509]     at assert (/project/tvl_adapters/adapters/protocol3adao/node_modules/ethers/lib.commonjs/utils/errors.js:149:15)
[2024-05-24, 09:51:40 UTC] {{task_log_fetcher.py:63}} INFO - [2024-05-24 09:51:14,509]     at FetchResponse.assertOk (/project/tvl_adapters/adapters/protocol3adao/node_modules/ethers/lib.commonjs/utils/fetch.js:839:32)
[2024-05-24, 09:51:40 UTC] {{task_log_fetcher.py:63}} INFO - [2024-05-24 09:51:14,509]     at JsonRpcProvider._send (/project/tvl_adapters/adapters/protocol3adao/node_modules/ethers/lib.commonjs/providers/provider-jsonrpc.js:890:18)
[2024-05-24, 09:51:40 UTC] {{task_log_fetcher.py:63}} INFO - [2024-05-24 09:51:14,509]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-05-24, 09:51:40 UTC] {{task_log_fetcher.py:63}} INFO - [2024-05-24 09:51:14,509]     at async /project/tvl_adapters/adapters/protocol3adao/node_modules/ethers/lib.commonjs/providers/provider-jsonrpc.js:281:40 {
[2024-05-24, 09:51:40 UTC] {{task_log_fetcher.py:63}} INFO - [2024-05-24 09:51:14,509]   code: 'SERVER_ERROR',
[2024-05-24, 09:51:40 UTC] {{task_log_fetcher.py:63}} INFO - [2024-05-24 09:51:14,509]   request: FetchRequest {},
[2024-05-24, 09:51:40 UTC] {{task_log_fetcher.py:63}} INFO - [2024-05-24 09:51:14,509]   response: FetchResponse {},

**Comment by bytes0xcr6** [comment]
@0xroll 
I just added extra providers to retry in case of error connection. This may be because the RPC is very saturated and it ends up returning 504.

PR with the changes: https://github.com/delta-hq/l2-lxp-liquidity-reward/pull/177
