### ISSUE TITLE
Connext - Issues

### ISSUE THREAD

**Issue by 0xroll** [delta-hq/l2-lxp-liquidity-reward#207]
hi @LayneHaber 

The address 0xdd507fecd5de6f5398060cc0404cb133f9048c3a has an unusually high WETH balance returned by the adapter.

please look into this.

also adapter has been failing for the past few days.

```
[2024-06-06, 13:17:40 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-06 13:17:05,800]     at async /project/tvl_adapters/adapters/connext/dist/index.js:51:28 {
[2024-06-06, 13:17:40 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-06 13:17:05,800]   [cause]: ConnectTimeoutError: Connect Timeout Error (attempted addresses: 3.18.62.180:443)
[2024-06-06, 13:17:40 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-06 13:17:05,800]       at onConnectTimeout (node:internal/deps/undici/undici:6635:28)
[2024-06-06, 13:17:40 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-06 13:17:05,800]       at node:internal/deps/undici/undici:6587:50
[2024-06-06, 13:17:40 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-06 13:17:05,800]       at Immediate._onImmediate (node:internal/deps/undici/undici:6619:13)
[2024-06-06, 13:17:40 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-06 13:17:05,800]       at process.processImmediate (node:internal/timers:478:21) {
[2024-06-06, 13:17:40 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-06 13:17:05,800]     code: 'UND_ERR_CONNECT_TIMEOUT'
[2024-06-06, 13:17:40 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-06 13:17:05,800]   }
[2024-06-06, 13:17:40 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-06 13:17:05,800] }
[2024-06-06, 13:17:40 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-06 13:17:05,800] An error occurred for block [object Object]: TypeError: fetch failed
[2024-06-06, 13:17:40 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-06 13:17:05,800]     at node:internal/deps/undici/undici:12502:13
[2024-06-06, 13:17:40 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-06 13:17:05,800]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-06-06, 13:17:40 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-06 13:17:05,800]     at async executeSubgraphQuery (/project/tvl_adapters/adapters/connext/dist/utils/subgraph.js:54:22)
[2024-06-06, 13:17:40 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-06 13:17:05,800]     at async getLpAccountBalanceAtBlock (/project/tvl_adapters/adapters/connext/dist/utils/subgraph.js:70:46)
```

**Comment by 0xroll** [comment]
@LayneHaber 

another issue with wrong balance : 0xc82c7d826b1ed0b2a4e9a2be72b445416f901fd1

**Comment by LayneHaber** [comment]
https://github.com/delta-hq/l2-lxp-liquidity-reward/pull/209#issuecomment-2195442113
