### ISSUE TITLE
Stargate - Issues

### ISSUE THREAD

**Issue by 0xroll** [delta-hq/l2-lxp-liquidity-reward#210]
hey @kyle-layerzero 

the adapter is having issue, please fix!

```
number   timestamp
[2024-06-05, 15:16:44 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-05 15:16:19,426] 0  5154879  1717513197
[2024-06-05, 15:16:44 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-05 15:16:19,426] 1  5156079  1717516797
[2024-06-05, 15:16:44 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-05 15:16:19,426] 2  5157279  1717520397
[2024-06-05, 15:16:44 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-05 15:16:19,426] 3  5158479  1717523997
[2024-06-05, 15:19:45 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-05 15:19:31,650] 2024-06-05 15:19:31,650 WARNING root An error occurred for block [object Object]: RangeError: Maximum call stack size exceeded
[2024-06-05, 15:19:45 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-05 15:19:31,650]     at /project/tvl_adapters/adapters/stargate/dist/index.js:81:24
[2024-06-05, 15:19:45 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-05 15:19:31,650]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-06-05, 15:19:45 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-05 15:19:31,650] An error occurred for block [object Object]: RangeError: Maximum call stack size exceeded
[2024-06-05, 15:19:45 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-05 15:19:31,650]     at /project/tvl_adapters/adapters/stargate/dist/index.js:81:24
[2024-06-05, 15:19:45 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-05 15:19:31,650]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-06-05, 15:19:45 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-05 15:19:31,650] An error occurred for block [object Object]: RangeError: Maximum call stack size exceeded
[2024-06-05, 15:19:45 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-05 15:19:31,650]     at /project/tvl_adapters/adapters/stargate/dist/index.js:81:24
[2024-06-05, 15:19:45 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-05 15:19:31,650]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-06-05, 15:19:45 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-05 15:19:31,650] An error occurred for block [object Object]: RangeError: Maximum call stack size exceeded
[2024-06-05, 15:19:45 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-05 15:19:31,650]     at /project/tvl_adapters/adapters/stargate/dist/index.js:81:24
[2024-06-05, 15:19:45 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-05 15:19:31,650]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-06-05, 15:19:45 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-05 15:19:31,650] 2024-06-05 15:19:31,650 INFO root
```

**Comment by kyle-layerzero** [comment]
@0xroll there's some changes since I last worked on this [here](https://github.com/delta-hq/l2-lxp-liquidity-reward/commit/eb4eb14b48b1c0b9daefa57eb29f262384d139c3). I'm running the code and not seeing the issue but I don't have all the details like what the `hourly_blocks.csv` is in the error case. There's definitely a suspect in the while loop to get user balances but I can't pin it down without some more details.

**Comment by 0xroll** [comment]
you can find the block numbers passed above

```
[2024-06-05, 15:16:44 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-05 15:16:19,426] 0  5154879  1717513197
[2024-06-05, 15:16:44 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-05 15:16:19,426] 1  5156079  1717516797
[2024-06-05, 15:16:44 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-05 15:16:19,426] 2  5157279  1717520397
[2024-06-05, 15:16:44 UTC] {{task_log_fetcher.py:63}} INFO - [2024-06-05 15:16:19,426] 3  5158479  1717523997
```

**Comment by kyle-layerzero** [comment]
@0xroll I took a look and found that some blocks have too many rows for the current implementation. I have an alternative here - https://github.com/delta-hq/l2-lxp-liquidity-reward/pull/245, let me know what you think.

**Comment by 0xroll** [comment]
@kyle-layerzero just reran and got this

```
[2024-07-03, 11:13:38 UTC] {{task_log_fetcher.py:63}} INFO - [2024-07-03 11:13:26,734]     chunks = self._reader.read_low_memory(nrows)
[2024-07-03, 11:13:38 UTC] {{task_log_fetcher.py:63}} INFO - [2024-07-03 11:13:26,734]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-07-03, 11:13:38 UTC] {{task_log_fetcher.py:63}} INFO - [2024-07-03 11:13:26,734]   File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
[2024-07-03, 11:13:38 UTC] {{task_log_fetcher.py:63}} INFO - [2024-07-03 11:13:26,735]   File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
[2024-07-03, 11:13:38 UTC] {{task_log_fetcher.py:63}} INFO - [2024-07-03 11:13:26,735]   File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
[2024-07-03, 11:13:38 UTC] {{task_log_fetcher.py:63}} INFO - [2024-07-03 11:13:26,735]   File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
[2024-07-03, 11:13:38 UTC] {{task_log_fetcher.py:63}} INFO - [2024-07-03 11:13:26,735]   File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
[2024-07-03, 11:13:38 UTC] {{task_log_fetcher.py:63}} INFO - [2024-07-03 11:13:26,735] pandas.errors.ParserError: Error tokenizing data. C error: Expected 7 fields in line 1001, saw 13
```

**Comment by kyle-layerzero** [comment]
@0xroll I've double checked a few cases on the ingestion side and am able to generate hundreds of thousands of rows. Based on that and the error message, are you sure there's an issue with the adapter code?

**Comment by kyle-layerzero** [comment]
@0xroll I found an issue and fixed it here - https://github.com/delta-hq/l2-lxp-liquidity-reward/pull/271

**Comment by 0xroll** [comment]
adapter working fine, closing this. tyvm @kyle-layerzero !!
