### ISSUE TITLE
LogX - Issues

### ISSUE THREAD

**Issue by 0xroll** [delta-hq/l2-lxp-liquidity-reward#244]
hi @TikeshFlint 

getting this error from the adapter

```
[2024-07-01, 12:09:29 UTC] {{ecs.py:225}} INFO - [2024-07-01 12:09:24,988]     number   timestamp
[2024-07-01, 12:09:29 UTC] {{ecs.py:225}} INFO - [2024-07-01 12:09:24,988] 0  4605699  1715860798
[2024-07-01, 12:09:29 UTC] {{ecs.py:225}} INFO - [2024-07-01 12:09:24,988] 1  4606899  1715864399
[2024-07-01, 12:09:29 UTC] {{ecs.py:225}} INFO - [2024-07-01 12:09:24,988] 2  4608099  1715867999
[2024-07-01, 12:09:29 UTC] {{ecs.py:225}} INFO - [2024-07-01 12:09:24,988] 3  4609299  1715871599
[2024-07-01, 12:09:29 UTC] {{ecs.py:187}} INFO - Status of the task is RUNNING
[2024-07-01, 12:09:35 UTC] {{ecs.py:187}} INFO - Status of the task is RUNNING
[2024-07-01, 12:09:41 UTC] {{ecs.py:187}} INFO - Status of the task is RUNNING
[2024-07-01, 12:09:47 UTC] {{ecs.py:187}} INFO - Status of the task is RUNNING
[2024-07-01, 12:09:53 UTC] {{ecs.py:225}} INFO - [2024-07-01 12:09:46,244] 2024-07-01 12:09:46,244 ERROR root 
[2024-07-01, 12:09:53 UTC] {{ecs.py:225}} INFO - [2024-07-01 12:09:46,244] Traceback (most recent call last):
[2024-07-01, 12:09:53 UTC] {{ecs.py:225}} INFO - [2024-07-01 12:09:46,244]   File "/project/main.py", line 107, in <module>
[2024-07-01, 12:09:53 UTC] {{ecs.py:225}} INFO - [2024-07-01 12:09:46,244]     main()
[2024-07-01, 12:09:53 UTC] {{ecs.py:225}} INFO - [2024-07-01 12:09:46,244]   File "/project/main.py", line 98, in main
[2024-07-01, 12:09:53 UTC] {{ecs.py:225}} INFO - [2024-07-01 12:09:46,245]     raise e
[2024-07-01, 12:09:53 UTC] {{ecs.py:225}} INFO - [2024-07-01 12:09:46,245]   File "/project/main.py", line 74, in main
[2024-07-01, 12:09:53 UTC] {{ecs.py:225}} INFO - [2024-07-01 12:09:46,245]     completed_process.check_returncode()
[2024-07-01, 12:09:53 UTC] {{ecs.py:225}} INFO - [2024-07-01 12:09:46,245]   File "/usr/local/lib/python3.12/subprocess.py", line 502, in check_returncode
[2024-07-01, 12:09:53 UTC] {{ecs.py:225}} INFO - [2024-07-01 12:09:46,245]     raise CalledProcessError(self.returncode, self.args, self.stdout,
[2024-07-01, 12:09:53 UTC] {{ecs.py:225}} INFO - [2024-07-01 12:09:46,245] subprocess.CalledProcessError: Command '['sh', '-c', 'cd ./tvl_adapters/adapters/logx && npm install && tsc && npm run start']' returned non-zero exit status 2.
```

**Comment by TikeshFlint** [comment]
Thanks for the information! 
can you please give some more context that you are getting step by step, so I can test in my local and see how we can resolve this.
@0xroll

**Comment by TikeshFlint** [comment]
Hey! can you please share the above information @0xroll 

Thanks!

**Comment by 0xroll** [comment]
@TikeshFlint 

on our end we just pass the block numbers in 

these are the blocks we passed

```
[2024-07-04, 07:10:43 UTC] {{ecs.py:225}} INFO - [2024-07-04 07:10:38,190]     number   timestamp
[2024-07-04, 07:10:43 UTC] {{ecs.py:225}} INFO - [2024-07-04 07:10:38,190] 0  4605699  1715860798
[2024-07-04, 07:10:43 UTC] {{ecs.py:225}} INFO - [2024-07-04 07:10:38,190] 1  4606899  1715864399
[2024-07-04, 07:10:43 UTC] {{ecs.py:225}} INFO - [2024-07-04 07:10:38,190] 2  4608099  1715867999
[2024-07-04, 07:10:43 UTC] {{ecs.py:225}} INFO - [2024-07-04 07:10:38,190] 3  4609299  1715871599
```

**Comment by TikeshFlint** [comment]
if you change this "number" name to "block_number" it will work.
should I change this in my end and make PR again ?

**Comment by 0xroll** [comment]
@TikeshFlint still failing

```
[2024-07-09, 09:09:20 UTC] {{ecs.py:225}} INFO - [2024-07-09 09:09:14,784]     number   timestamp
[2024-07-09, 09:09:20 UTC] {{ecs.py:225}} INFO - [2024-07-09 09:09:14,784] 0  4605699  1715860798
[2024-07-09, 09:09:20 UTC] {{ecs.py:225}} INFO - [2024-07-09 09:09:14,784] 1  4606899  1715864399
[2024-07-09, 09:09:20 UTC] {{ecs.py:225}} INFO - [2024-07-09 09:09:14,784] 2  4608099  1715867999
[2024-07-09, 09:09:20 UTC] {{ecs.py:225}} INFO - [2024-07-09 09:09:14,784] 3  4609299  1715871599
[2024-07-09, 09:09:20 UTC] {{ecs.py:187}} INFO - Status of the task is RUNNING
[2024-07-09, 09:09:26 UTC] {{ecs.py:187}} INFO - Status of the task is RUNNING
[2024-07-09, 09:09:32 UTC] {{ecs.py:187}} INFO - Status of the task is RUNNING
[2024-07-09, 09:09:38 UTC] {{ecs.py:225}} INFO - [2024-07-09 09:09:35,471] 2024-07-09 09:09:35,471 ERROR root 
[2024-07-09, 09:09:38 UTC] {{ecs.py:225}} INFO - [2024-07-09 09:09:35,471] Traceback (most recent call last):
[2024-07-09, 09:09:38 UTC] {{ecs.py:225}} INFO - [2024-07-09 09:09:35,471]   File "/project/main.py", line 107, in <module>
[2024-07-09, 09:09:38 UTC] {{ecs.py:225}} INFO - [2024-07-09 09:09:35,471]     main()
[2024-07-09, 09:09:38 UTC] {{ecs.py:225}} INFO - [2024-07-09 09:09:35,471]   File "/project/main.py", line 98, in main
[2024-07-09, 09:09:38 UTC] {{ecs.py:225}} INFO - [2024-07-09 09:09:35,471]     raise e
[2024-07-09, 09:09:38 UTC] {{ecs.py:225}} INFO - [2024-07-09 09:09:35,471]   File "/project/main.py", line 74, in main
[2024-07-09, 09:09:38 UTC] {{ecs.py:225}} INFO - [2024-07-09 09:09:35,471]     completed_process.check_returncode()
[2024-07-09, 09:09:38 UTC] {{ecs.py:225}} INFO - [2024-07-09 09:09:35,471]   File "/usr/local/lib/python3.12/subprocess.py", line 502, in check_returncode
[2024-07-09, 09:09:38 UTC] {{ecs.py:225}} INFO - [2024-07-09 09:09:35,472]     raise CalledProcessError(self.returncode, self.args, self.stdout,
[2024-07-09, 09:09:38 UTC] {{ecs.py:225}} INFO - [2024-07-09 09:09:35,472] subprocess.CalledProcessError: Command '['sh', '-c', 'cd ./tvl_adapters/adapters/logx && npm install && tsc && npm run start']' returned non-zero exit status 2.
```

**Comment by TikeshFlint** [comment]
Hey please tell me how you are running this in your local so I can do it by my own

**Comment by 0xroll** [comment]
hey @TikeshFlint on our end we just get the list of block numbers and pass it into the adapter. i can share with you the full logs, maybe lets discuss on telegram? my handle is @jh_onchain

**Comment by TikeshFlint** [comment]
cool, pinged you on TG.
