### ISSUE TITLE
SATORI Problem On Querying

### ISSUE THREAD

**Issue by RamonReis** [delta-hq/l2-lxp-liquidity-reward#93]
subgraphUrl: 'https://api.goldsky.com/api/public/project_cltzggx5i40gi01p3ezjv94bc/subgraphs/satori-linea/v0.0.1/gn'
https://github.com/delta-hq/l2-lxp-liquidity-reward/blob/main/adapters/satori/src/sdk/subgraphDetailsV2.ts#L24

![image](https://github.com/delta-hq/l2-lxp-liquidity-reward/assets/3669322/35ea216f-9bd5-4160-80bd-40f1b0e32d18)

**Comment by miler012** [comment]
it is work now. the subgragh suspend . and it working now

**Comment by nitish-91** [comment]
@miler012 we are seeing this error. Not able to ingest satori data


An error occurred for block [object Object]: Error: Error fetching data from subgraph 
[2024-05-08, 21:17:29 UTC] {{task_log_fetcher.py:63}} INFO - [2024-05-08 21:16:59,441] Status code: 429
[2024-05-08, 21:17:29 UTC] {{task_log_fetcher.py:63}} INFO - [2024-05-08 21:16:59,441] Status Text: Too Many Requests
[2024-05-08, 21:17:29 UTC] {{task_log_fetcher.py:63}} INFO - [2024-05-08 21:16:59,441]     at getUserTVLByBlock (/project/tvl_adapters/adapters/satori/dist/sdk/subgraphDetailsV2.js:27:19)
[2024-05-08, 21:17:29 UTC] {{task_log_fetcher.py:63}} INFO - [2024-05-08 21:16:59,441]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-05-08, 21:17:29 UTC] {{task_log_fetcher.py:63}} INFO - [2024-05-08 21:16:59,441]     at async /project/tvl_adapters/adapters/satori/dist/index.js:55:28
[2024-05-08, 21:17:29 UTC] {{task_log_fetcher.py:63}} INFO - [2024-05-08 21:16:59,441] 2024-05-08 21:16:59,441 INFO root 
[2024-05-08, 21:17:29 UTC] {{task_log_fetcher.py:63}} INFO - [2024-05-08 21:16:59,441] up to date, audited 24 packages in 472ms

**Comment by miler012** [comment]
ok we are working on it
