### ISSUE TITLE
Sparta - stale data due to graphql logic

### ISSUE THREAD

**Issue by 0xroll** [delta-hq/l2-lxp-liquidity-reward#98]
@spaceh3ad 

as discussed, please proceed with the new changes for the query to get latest sync

**Comment by spaceh3ad** [comment]
#99

**Comment by RamonReis** [comment]
We're experiencing the following error:
2024-05-10 08:50:29,577 INFO root Blocks fetched successfully.
2024-05-10 08:50:29,585 INFO root Processing blocks:
    number   timestamp
0  4414943  1715288397
2024-05-10 08:50:34,022 WARNING root (node:836583) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
An error occurred for block [object Object]: RangeError: The number 480483210.34764194 cannot be converted to a BigInt because it is not an integer
    at BigInt (<anonymous>)
    at adapters/sparta/dist/index.js:87:26
    at Array.forEach (<anonymous>)
    at adapters/sparta/dist/index.js:75:48
    at Array.forEach (<anonymous>)
    at calculateUserReservePortion (adapters/sparta/dist/index.js:68:32)
    at processBlockData (adapters/sparta/dist/index.js:22:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getUserTVLByBlock (adapters/sparta/dist/index.js:215:18)
    at async adapters/sparta/dist/index.js:272:28

**Comment by nitish-91** [comment]
@spaceh3ad please check this.

**Comment by spaceh3ad** [comment]
https://github.com/spaceh3ad/l2-lxp-liquidity-reward/blob/main/adapters/sparta/src/index.ts#L238

```diff
function convertToOutputDataSchema(
  userPositions: UserPosition[]
): OutputDataSchemaRow[] {
  return userPositions.map((userPosition) => {
    return {
      block_number: userPosition.block_number,
      timestamp: userPosition.timestamp,
      user_address: userPosition.user,
      token_address: userPosition.token,
+    token_balance: BigInt(userPosition.balance), // Ensure balance is treated as bigint
      token_symbol: "", // You may want to fill this based on additional token info you might have
      usd_price: 0, // Adjust if you need to calculate this value or pull from another source
    };
  });
}
```
 not sure about this issue I am saving as bigint as was desribed in readme

**Comment by nitish-91** [comment]
@spaceh3ad according to the error. the data you are getting from api/graph is float and you are trying to convert it to bigint. Can you please run the adapter on your side with below examples, and few more to replicate and fix the issue.

 ```
 number   timestamp
[2024-05-10, 13:13:13 UTC] {{task_log_fetcher.py:63}} INFO - [2024-05-10 13:12:44,814] 0  4414943  1715288397
[2024-05-10, 13:13:13 UTC] {{task_log_fetcher.py:63}} INFO - [2024-05-10 13:12:44,814] 1  4416143  1715291997
[2024-05-10, 13:13:13 UTC] {{task_log_fetcher.py:63}} INFO - [2024-05-10 13:12:44,814] 2  4417343  1715295597
[2024-05-10, 13:13:13 UTC] {{task_log_fetcher.py:63}} INFO - [2024-05-10 13:12:44,814] 3  4418542  1715299199
```

**Comment by RamonReis** [comment]
The issue seems to have been resolved, thanks!
